modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "Better hashing algorithm for Vec3i & BlockPos"
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "efficient_hashing.mixins.json"